version: '3.3'

services:

  application:
    restart: always
    image: flairsoft/application
    build:
      context: .
      dockerfile: ./src/dockerFile
    ports:
      - "8002:3000"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      flairsoft:
        aliases:
          - ai.flairsoft.local

  postgres:
    restart: always
    build:
      context: ./docker_init
      dockerfile: postgres.Dockerfile
    command: postgres -c "max_connections=500"
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      - POSTGRES_PASSWORD=flairsoft
      - POSTGRES_USER=flairsoft
    networks:
      flairsoft:
        aliases:
          - postgres.flairsoft.local

  gateway:
    restart: always
    image: flairsoft/gateway
    build:
      context: .
      dockerfile: ./src/gateway.dockerFile
    ports:
      - "8001:3500"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      flairsoft:
        aliases:
          - ai.flairsoft.local

  migration:
    restart: always
    image: flairsoft/migration
    build:
      context: .
      dockerfile: ./migration/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      flairsoft:
        aliases:
          - migration.flairsoft.local

volumes:
  pgdata:

networks:
  flairsoft:
    driver: bridge
#    name: flairsoft.local
