STATUS = {
    "UNPROCESSED": "UNPROCESSED",
    "CONVERTED": "CONVERTED",
    "REMOVED_NOISE": "REMOVED_NOISE",
    "OCR": "OCR",
    "FINISHED": "FINISHED"
}

TABLE_NAMES = {
    "image": "image",
    "document": "document"
}


BUCKET_NAMES = {
    "UNPROCESSED": "UNPROCESSED",
    "CONVERTED": "CONVERTED",
    "REMOVED_NOISE": "REMOVED_NOISE",
    "OCR": "OCR",
    "FINISHED": "FINISHED"
}
